#!/usr/bin/env python3
"""Prune languages without runtimes from a Serena project.yml.

Reads the whitelist from works_in_container.json (generated by
generate_whitelist.py or maintained manually). Removes any detected
languages not in the whitelist.

Usage: prune_langs.py <project.yml> [whitelist.json]
"""
import json
import os
import sys


def load_whitelist(path: str) -> set[str]:
    with open(path) as f:
        data = json.load(f)
    return frozenset(data["languages"])


def prune(yml_path: str, whitelist: set[str]) -> None:
    with open(yml_path) as f:
        lines = f.readlines()

    # Find the languages block: "languages:\n" followed by "- <lang>\n" lines
    start = None
    end = None
    for i, line in enumerate(lines):
        if line.startswith("languages:"):
            start = i
        elif start is not None and line.startswith("- "):
            end = i + 1
        elif start is not None and end is not None and (line.strip() == "" or line.startswith("#")):
            break

    if start is None or end is None:
        return

    # Extract current languages
    current = []
    for j in range(start + 1, end):
        lang = lines[j].lstrip("- ").strip()
        if lang:
            current.append(lang)

    kept = [l for l in current if l in whitelist]
    removed = [l for l in current if l not in whitelist]

    if removed:
        new_lines = ["languages:\n"]
        for lang in kept:
            new_lines.append(f"- {lang}\n")
        lines[start:end] = new_lines

        with open(yml_path, "w") as f:
            f.writelines(lines)

        print(f"  Pruned {', '.join(sorted(removed))} from {yml_path}")


if __name__ == "__main__":
    yml_path = sys.argv[1]
    json_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "works_in_container.json"
    )
    whitelist = load_whitelist(json_path)
    prune(yml_path, whitelist)
